# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: A sample web project
description: >-
  This is a much longer description that needs to be filled in
baseurl: "/" # the subpath of your site, e.g. /blog
domain: example.com
url: "https://www.example.com" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics_id: UA-18715035-1
fonts: Montserrat&family=Open+Sans
theme_color: "#a970ff"
theme_color_background: "#000000"
authors:
  - name: Kurtis Rainbolt-Greene
    role: Programmer
    contact: kurtis@rainbolt-greene.online
credits: []

# Build settings
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
include:
  - .well-known
  - .nojekyll
exclude:
  - docs
  - CONDUCT.md
  - LICENSE.txt
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
